### ISSUE TITLE
Cannot interact with the main application after "New Prompt" shortcut

### ISSUE THREAD

**Issue by BrunoGeorgevich** [nbonamy/witsy#25] opened 2024-12-13 15:05 UTC
I love witsy and i've being using everyday.

I've found a new bug.

## To reproduce:
 1) Open the main Witsy application (chat).
 1) Now open the "New Prompt" function using a shortcut.
 1) Hit ESC to close the "New Prompt" dialog.
 1) Now you are not able to interact with the main application.

## Demo

https://github.com/user-attachments/assets/93631af1-202e-4171-aaba-542d09e4df1d

## OS
Windows 11

## Possible cause
It seems you are likely hiding the main application and preventing interaction with it when the "New Prompt" dialog appears. However, after that, you are not re-enabling interaction with the main application; you are only making it visible again.

What do you think?

**Comment by nbonamy** [comment] 2024-12-13 15:30
Hum. You know what I was thinking of not hiding any windows at all when "New Prompt" is called. This causes more issues than needed. Will look into it!

**Comment by BrunoGeorgevich** [comment] 2024-12-13 15:32
> Hum. You know what I was thinking of not hiding any windows at all when "New Prompt" is called. This causes more issues than needed. Will look into it!

Seems to be a good approach.

**Comment by nbonamy** [comment] 2024-12-16 16:27
Hopefully fixed in 1.27.4

**Comment by BrunoGeorgevich** [comment] 2024-12-16 16:34
I've confirmed that the issue was resolved in version 1.27.4. Thanks. It appears the same problem is also present in the "AI commands" shortcut, likely due to the same underlying cause. Should I create a new issue?

**Comment by nbonamy** [comment] 2024-12-16 16:47
Yes please because the issue is a bit more complex as AI command need to interact with the underlying app

**Closed by nbonamy** 2024-12-16 16:47 UTC
Labels: bug
